---
title: Yr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: staff
  values:
    role: 
    image_file: 
- scope:
    path: ''
  values:
    layout: default
description: Yr
