---
title: Yr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  staff:
    title: Staff
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: staff
  values:
    name: 
    role: 
    blurb: 
